# Generated by Django 3.2.4 on 2021-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('rating', models.FloatField()),
                ('owner_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('license', models.TextField()),
            ],
        ),
    ]
