# Generated by Django 3.2.4 on 2021-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210622_0535'),
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_images',
            field=models.ManyToManyField(related_name='detailed_images', to='shop.Image'),
        ),
    ]
